packages:
  - "apps/*"
  - "packages/*"
  - "e2e/*"

allowBuilds:
  esbuild: true
  lefthook: true
  sharp: true
  workerd: true

catalogMode: prefer

catalogs:
  default:
    "@biomejs/biome": "2.4.11"
    "@commitlint/cli": "^20.5.0"
    "@commitlint/config-conventional": "^20.5.0"
    "@moonrepo/cli": "^2.2.0"
    "@playwright/test": "1.59.1"
    "lefthook": "^2.1.5"
    "portless": "0.10.3"
cleanupUnusedCatalogs: true
