# yaml-language-server: $schema=../cache/schemas/tasks.json

inheritedBy:
  layer: "application"

tasks:
  dev:
    command: "bun portless run --force --name $project bun vite"
    deps:
      - "portless:proxy"
    options:
      cache: false
      persistent: true
      runInCI: false
