# yaml-language-server: $schema=../cache/schemas/tasks.json

inheritedBy:
  file: "biome.json"

tasks:
  lint:
    command: "bun biome lint --no-errors-on-unmatched --files-ignore-unknown=true ."
    inputs:
      - "src/**/*"
      - "biome.json"
      - "/biome.json"
