# yaml-language-server: $schema=../cache/schemas/tasks.json

inheritedBy:
  file: "playwright.config.ts"

tasks:
  e2e:
    command: "bun playwright test"
    deps:
      - "^:build"
      - "playwright:install-browsers"
    inputs:
      - "src/**/*"
      - "tests/**/*"
      - "playwright.config.ts"
      - "/tsconfig.json"
    outputs:
      - "playwright-report"
      - "test-results"
    options:
      runInCI: true
