# yaml-language-server: $schema=../cache/schemas/tasks.json

inheritedBy:
  file: "tsup.config.ts"

tasks:
  build:
    command: "bun tsup"
    deps:
      - "~:typecheck"
      - "~:lint"
    inputs:
      - "src/**/*"
      - "tsup.config.ts"
      - "tsconfig.json"
    outputs:
      - "dist"
