$schema: 'https://moonrepo.dev/schemas/tasks.json'

inheritedBy:
  file: 'tsconfig.json'

tasks:
  typecheck:
    command: 'pnpm tsc --noEmit --pretty'
    inputs:
      - 'src/**/*'
      - 'tsconfig.json'
      - '/tsconfig.json'
      - '/tsconfig.options.json'
