# yaml-language-server: $schema=../cache/schemas/tasks.json

inheritedBy:
  file: "tsconfig.json"

tasks:
  typecheck:
    command: "bun tsc --pretty"
    inputs:
      - "src/**/*"
      - "tsconfig.json"
      - "/tsconfig.json"
      - "/tsconfig.options.json"
