# yaml-language-server: $schema=../cache/schemas/tasks.json

inheritedBy:
  file: "wrangler.json"

tasks:
  deploy:
    command: "bun wrangler deploy"
    deps:
      - "~:build"
    inputs:
      - "src/**/*"
      - "wrangler.json"
