$schema: 'https://moonrepo.dev/schemas/tasks.json'

inheritedBy:
  file: 'wrangler.json'

tasks:
  deploy:
    command: 'pnpm wrangler deploy'
    deps:
      - '~:build'
    inputs:
      - 'src/**/*'
      - 'wrangler.json'
