name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  ci:
    name: "CI"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Moon
        uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true
          auto-setup: true
          cache: true
          cache-base: main

      - name: Run CI
        run: moon ci --summary
