name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  ci:
    name: "CI"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PNPM
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Cache Moon Task Results
        uses: actions/cache@v4
        with:
          path: .moon/cache
          key: moon-cache-${{ runner.os }}-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            moon-cache-${{ runner.os }}-${{ github.ref_name }}-
            moon-cache-${{ runner.os }}-

      - name: Run CI
        run: pnpm moon ci --summary

